<?php

namespace App\ApiResource;

use ApiPlatform\Metadata\ApiResource;

#[ApiResource]
class ExerciseGroupsGenerating
{
    public function getId(): int
    {
        return 1; // TODO: Change the autogenerated stub
    }
}
